---
- name: Install additional development tools
  dnf:
    state: present
    name:
      - tealdeer
      - bat
      - fzf
      - exa
      - ripgrep
      - sqlite
      - zoxide
      - direnv

- name: Install extra dependencies
  dnf:
    state: present
    name:
      - ImageMagick
      - ImageMagick-doc
      - ImageMagick-libs
      - hyperfine
      - libtree-sitter
      - newsboat
      - recoll
      - recoll-gssp
      - recoll-kio
      - starship
      - yt-dlp

- name: Install documentation tools
  package:
    state: present
    name:
      - asciidoctor
      - editorconfig
