---
- name: Install additional development tools
  dnf:
    state: present
    name:
      - tealdeer
      - bat
      - fzf
      - exa
      - gopass
      - ripgrep
      - sqlite
      - zoxide
      - direnv

- name: Install extra dependencies
  dnf:
    state: present
    name:
      - hyperfine
      - libtree-sitter
      - newsboat
      - starship
      - yt-dlp

- name: Install documentation tools
  package:
    state: present
    name:
      - asciidoctor
      - editorconfig
