---
- name: Install dconf keyfiles
  copy:
    src: "{{ role_path }}/files/dconf/"
    dest: "{{ '/etc/dconf/db/local.d' if ansible_facts['distribution'] == 'Fedora' else '/etc/dconf/db/a-happy-gnome.d' }}"

- name: Set 'user' dconf profile with the custom GNOME config
  ansible.builtin.shell: grep "system-db:a-happy-gnome" && echo "system-db:a-happy-gnome" >> /etc/dconf/profile/user
  when: ansible_facts["distribution"] != "Fedora"

- name: Update dconf database
  ansible.builtin.shell: dconf update

- name: Install GNOME extension manager
  flatpak:
    state: present
    name: "{{ item }}"
    remote: flathub
  loop:
    - com.mattjakeman.ExtensionManager
