# TODO:
# * Configure GNOME extensions
# * Configure the Fedora host with custom systemd units
# * Custom session variables
# This is the playbook for a Fedora Workstation post-installation.
---
- name: foo-dogsquared's Fedora workstation
  hosts: workstation
  become: yes

  roles:
    - role: system/base
      tags:
        - base
        - dev
        - system
    - role: system/i18n
      tags:
        - base
        - extra
    - role: system/fonts
      tags:
        - base
        - system
    - role: system/flatpak
      tags:
        - desktop
        - system
        - flatpak
    - role: system/external_backup
      tags:
        - system
        - setup
        - backup
    - role: apps/emacs
      tags:
        - apps

  tasks:
    - name: Enable copr repositories
      community.general.copr:
        state: enabled
        name: "{{ item }}"
      loop:
        - cappyishihara/opentabletdriver
        - atim/lazygit
        - fale/gopass
        - peterwu/iosevka

    # Package installations.
    - name: Install packages from enabled copr repositories
      dnf:
        state: present
        name:
          - lazygit
          - opentabletdriver
          - golang-github-gopasspw-gopass
          - iosevka-fonts
          - iosevka-curly-fonts
          - iosevka-curly-slab-fonts
          - iosevka-slab-fonts
          - iosevka-etoile-fonts

    - name: Install RPM development tools
      dnf:
        state: present
        name:
          - rpm-build
          - go-rpm-macros

    - name: Install web-related tools
      dnf:
        state: present
        name:
          - thunderbird
          - chromium
          - firefox

    - name: Install Fedora COPR dev't tools
      dnf:
        state: present
        name:
          - copr-cli
          - dnf-plugins-core

    - name: Install Ansible
      dnf:
        state: present
        name:
          - ansible
          - ansible-doc
          - ansible-collection-community-general
          - python3-psutil
