# TODO:
# * Custom session variables
---
- name: foo-dogsquared's Fedora workstation
  hosts: workstation
  become: yes

  roles:
    - role: system/gnome
      tags:
        - base
        - desktop
        - system

    - role: system/i18n
      tags:
        - desktop

    - role: system/external_backup
      tags:
        - system

    - role: system/flatpak
      tags:
        - system
        - desktop
        - flatpak

  tasks:
    - name: Install various third-party repos
      ansible.builtin.get_url:
        url: "{{ item }}"
        dest: /etc/yum.repos.d
      loop:
        - "https://copr.fedorainfracloud.org/coprs/cappyishihara/opentabletdriver/repo/fedora-36/cappyishihara-opentabletdriver-fedora-36.repo"
        - "https://copr.fedorainfracloud.org/coprs/atim/lazygit/repo/fedora-36/atim-lazygit-fedora-36.repo"
      tags:
        - base
        - system

    - name: Install layered packages
      community.general.rpm_ostree_pkg:
        state: present
        name:
          - ansible
          - distrobox
          - borgmatic
          - gnome-boxes
          - kitty
          - neovim
          - openssl

          # Making this usable for binging movies.
          - gstreamer1-plugin-openh264

          # This is not a part of the base repos.
          - opentabletdriver
          - lazygit
      tags:
        - base
        - system
